### ISSUE TITLE
elem.clear() not clearing the last digit

### ISSUE THREAD

**Issue by Olivr3** [arunghosh/react-pin-input#8] opened 2018-01-02 12:02 UTC
I try to clear the input fields after `onComplete` is called

```
<PinInput
        length={4}
        type="numeric"
        ref={p => pin = p}
        onComplete={(value) => {
          // debugger
          pin.clear()
          props.onComplete(value)
        }}
      />
```
It clears the first three digits but not for the last input field.
Please see the image.
![screenshot from 2018-01-02 12-01-51](https://user-images.githubusercontent.com/20702895/34483194-c73f3ae0-efb4-11e7-89f0-49e0978c72f7.png)

**Comment by arunghosh** [comment] 2018-01-03 03:26
@Olivr3 Thanks for sharing the issue. 

The issue is fixed in **react-pin-input@0.6.2** via [commit](https://github.com/arunghosh/react-pin-input/commit/ab95b83f8b112bb803685459916565104a39511d)

**Comment by Olivr3** [comment] 2018-01-03 08:56
@arunghosh
Thank you for your comment.
It looks like that there is something broken in the latest package **0.6.2** .
The styling and the methods ( `onComplete`, `onChange` ) all stopped working after I upgraded to the latest.  
Please see image. 
![bug](https://user-images.githubusercontent.com/20702895/34514186-fb4792b0-f063-11e7-802f-6fcce20ecc38.png)

**Comment by arunghosh** [comment] 2018-01-03 11:18
@Olivr3 Sorry for that. There was a merge request to update change via props. But that wasn't backward compatible. I have fixed the style issue in **react-pin-input@0.6.3**.

Can you confirm the fix?
Thanks.

**Comment by Olivr3** [comment] 2018-01-03 13:02
@arunghosh I confirm that the style was fixed, but the `onComplete` method has stopped working. Also, I need to hit `TAB` key in order to go to the next input field as before it would jump to the next input field automatic.

**Comment by arunghosh** [comment] 2018-01-03 13:52
@Olivr3 which browser/environment are you testing? It's working when I tested.

**Comment by Olivr3** [comment] 2018-01-05 11:05
@arunghosh Sry for the late reply 

"react-pin-input": "^0.5.2" works fine 
"react-pin-input": "^0.6.3" methods not working 

Here are the specs
Ubuntu 16.04 LTS 
Google Chrome Version 63.0.3239.108 
&
Firefox QUantum Version 57.0.3 (64-bit)

**Comment by arunghosh** [comment] 2018-01-05 13:26
@Olivr3 I couldn't reproduce the issue. By analyzing the code difference, I have removed `inputMode` attribute. Can you check if that solved the issue in **react-pin-input@0.6.3**?

**Comment by Olivr3** [comment] 2018-01-05 13:58
@arunghosh 
I am afraid to say that the problem still persists. 
Here are steps I took to test 

yarn upgrade **react-pin-input@0.6.3**
copied the component that is on GitHub and tested it out.

```
<PinInput 
  length={4} 
  secret 
  onChange={(value, index) => { console.log('value'); }} 
  type="numeric" 
  style={{padding: '10px'}}  
  inputStyle={{borderColor: 'red'}}
  inputFocusStyle={{borderColor: 'blue'}}
  onComplete={(value, index) => { console.log('onComplete'); }}
/>
```
`onChange` and `onComplete` are not called for some reason. In version **react-pin-input": "^0.5.2" works fine** these actions work fine.

Please see the image. 

![screenshot from 2018-01-05 13-57-09](https://user-images.githubusercontent.com/20702895/34612169-6a895876-f220-11e7-8a63-c09e81fb2be9.png)

Hope that helps

**Comment by arunghosh** [comment] 2018-01-05 14:29
@Olivr3 Sorry to bother you again. Can you check if the issue is solved in react-pin-input@**0.6.41**?

**Comment by Olivr3** [comment] 2018-01-05 15:58
@arunghosh so version **0.6.41** version is working fine. Good Job.
However, the last digit doesn't get cleared `onComplete`.

`onComplete={(value) => {
          // debugger
          pin.clear() -----> only clears the first 3 digits
          props.onComplete(value)}}`

![passcode](https://user-images.githubusercontent.com/20702895/34616815-3e44a4c6-f231-11e7-9b9d-96b519995035.png)

**Comment by arunghosh** [comment] 2018-01-05 16:31
@Olivr3  Can you check if the last bit clearing issue is fixed in react-pin-input@**0.6.42**?

**Comment by Olivr3** [comment] 2018-01-05 16:59
@arunghosh it looks like that **0.6.42** is broken. The methods `clear()` `onComplete()` stopped to work again. 

```
<PinInput
        length={4}
        type="numeric"
        ref={p => pin = p}
        onComplete={(value) => {
          // debugger
          pin.clear()
          props.onComplete(value)
        }}
      />
```

**Comment by arunghosh** [comment] 2018-01-05 17:24
@Olivr3 Do you need to hit tab to move from one field to another?

**Comment by arunghosh** [comment] 2018-01-05 17:34
@Olivr3 The change in minimal. This is the [commit](https://github.com/arunghosh/react-pin-input/commit/efd86a60f341c11328d59e847418743abe26d7ba).

Moved the invoke of `onChange` inside callback of `setState`. That shouldn't break. And I am not able to reproduce the issue you are getting.

**Comment by Olivr3** [comment] 2018-01-08 08:29
@arunghosh Morning!

Yes, I do need to hit tab to move from one field to another.
I see, which browser are you testing it?

Could you send me the component with the props you are using it to test?

**Comment by arunghosh** [comment] 2018-01-08 08:48
@Olivr3 I tested on Firefox Quantum 57.0.4 and Chrome 63.

The way I tested using the code in the [example folder](https://github.com/arunghosh/react-pin-input/blob/master/example/index.js). 
```
import React from 'react';
import ReactDOM from 'react-dom';
import PinInput from '../src';

let pin;

ReactDOM.render(
  <div>
    <PinInput
      length={5}
      focus
      secret
      ref={p => (pin = p)}
      type="numeric"
      onChange={v => console.log(v)}
      onComplete={v => alert(v)}
    />
    <button onClick={() => pin.clear()}>Clear</button>
  </div>,
  document.getElementById('app'),
);
```
Or you can clone this project and run 
```
npm install
npm run dev
```

**Comment by Olivr3** [comment] 2018-01-08 14:02
@arunghosh I've included the example above in my project and it didn't work. 

I am using an old version of React `"react": "^15.4.2"`. Do you think that could be the issue?

**Comment by arunghosh** [comment] 2018-01-08 15:14
@Olivr3 It's the version. I was able to reproduce the issue with 15.4.5. It is working for > 16.

Let me get deeper into the issue. Thank you for pointing out the version change.

**Comment by Olivr3** [comment] 2018-01-08 15:55
@arunghosh sure. I am glad I could help. I can't upgrade to version 16 at the moment as it will break a bunch of stuff.

**Comment by arunghosh** [comment] 2018-01-09 10:07
@Olivr3 The latest version(react-pin-input@**0.6.5**) should work with react@15.4.2

**Comment by Olivr3** [comment] 2018-01-10 08:58
The issue has been fixed.

Well done.

**Closed** 2018-01-10 08:58 UTC
